# Generated by Django 4.2.13 on 2024-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dog_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(default=1, max_length=6, verbose_name='male'),
            preserve_default=False,
        ),
    ]
